/** Shared mutable application state (single source of truth). */
export const state = {
  projects: [],
  currentProjectId: 'project_personal',
  agentRuns: [],
  activeRunId: null,
  chats: [],
  currentChatId: null,
  messages: [],
  codeChats: [],
  codeCurrentChatId: null,
  forgeChats: [],
  forgeCurrentChatId: null,
  _normalMessages: [],
  _normalCurrentChatId: null,
  _codeMessages: [],
  _codeCurrentChatId: null,
  _forgeMessages: [],
  _forgeCurrentChatId: null,
  pendingImages: [],
  pendingFiles: [],
  streaming: false,
  abort: null,
  tab: 'chats',
  agents: [],
  activeAgentId: null,
  replyTo: null,
  editing: null,
  compareMode: false,
  slashOpen: false,
  slashIndex: 0,
  templates: [],
  activeTemplateId: null,
};
